jobs:
  - name: execute_tasks_list
    type: runSh
    runtime:
      architecture: x86_64
      os: Ubuntu_16.04
      container: true
    steps:
      - IN: reg_dh_ric03uec
      - IN: scaler
      - TASK:
          name: host_check_OS
          runtime:
            container: false
          script: 
            - docker images | grep busybox
            - uname -a
            - df -h
            - cat /etc/os-release
            - env
      - TASK:
          name:  container_check_OS
          runtime:
            options:
              imageName: drydock/u14pytall
              imageTag: master
          script: 
            - echo "Checking container os version"
            - cat /etc/*-release
            - df -h
            - env
    on_success:
      - script: echo "successfully completed"      
    on_failure:
      - script: echo "Oops !!! something went wrong"      
    flags:
      - runSh
