jobs:
  - name: execute_tasks_list
    type: runSh
    runtime:
      architecture: x86_64
      os: Ubuntu_16.04
      container: true
    steps:
      - IN: reg_dh_ric03uec
      - IN: scaler
      - TASK:
          name: host_check_OS
          runtime:
            container: false
            options:
              env:
                - ENV1: VALUE1
                - ENV2: VALUE2
          script: 
            - docker images | grep busybox
            - uname -a
            - df -h
            - cat /etc/os-release
            - env
      - TASK:
          name:  container_check_OS
          runtime:
            options:
              imageName: drydock/u14pytall
              imageTag: master
          script: 
            - echo "Checking container os version"
            - cat /etc/*-release
            - df -h
            - env
            
      - TASK:
          runtime:
            options:
              imageName: drydock/u14pytall
              imageTag: master
          script: 
            - echo "sleeping for a while..."
            - sleep 60
      - OUT: image_version
    on_success:
      - script: echo "successfully completed"      
    on_failure:
      - script: echo "Oops !!! something went wrong"      
    flags:
      - runSh

  - name: failed_job
    type: runSh
    runtime:
      architecture: x86_64
      os: Ubuntu_16.04
      container: false
    steps:
      - IN: reg_dh_ric03uec
      - IN: scaler
      - IN: execute_tasks_list
      - TASK:
          name: host_check_OS
          runtime:
            options:
              env:
                ENV5: VALUE5
                ENV6: VALUE6
          script: 
            - uname -a
            - df -h
            - cat /etc/os-release
            - this is an invalid command, should fail            
    on_success:
      - script: echo "successfully completed"      
    on_failure:
      - script: echo "Oops !!! something went wrong"      
    flags:
      - runSh
