jobs:
  - name: non_grisham_job
    type: runSh
    steps:
      - IN: sample_python_runCI
      - IN: reg_dh_ric03uec
        switch: off
      - IN: global_state
        switch: off
      - TASK:
        - script: echo 'This is task in old format'
        - script: ls -alh
        - script: env
        - script: df -h
    on_success:
      - script: echo 'succeeded'
    on_failure:
      - script: echo 'failed'
    flags:
      - runsh

  - name: docker_build_host
    type: runSh
    runtime:
      architecture: x86_64
      os: Ubuntu_16.04
      container: false
    steps:
      - IN: repo_sample_python
      - IN: reg_dh_ric03uec
        switch: off
      - TASK:
          name: docker build on the host
          script:
            - pushd $BUILD_DIR/IN/repo_sample_python/gitRepo
            - ls -atlh
            - docker build -t ric03uec/sample_python:grisham .
            - docker images
            - popd
      - OUT: image_sample_python
    on_success:
      - script: echo 'succeeded'
    on_failure:
      - script: echo 'failed'
    flags:
      - runsh

  - name: docker_build_container
    type: runSh
    runtime:
      architecture: x86_64
      os: Ubuntu_16.04
    steps:
      - IN: repo_sample_python
        switch: off
      - IN: reg_dh_ric03uec
        switch: off
      - TASK:
          name: docker build in a container
          script:
            - pushd $BUILD_DIR/IN/repo_sample_python/gitRepo
            - ls -atlh
            - export IMAGE_NAME=ric03uec/sample_python:grisham.$BUILD_NUMBER
            - docker build -t $IMAGE_NAME .
            - docker images
            - shipctl post_resource_state "image_sample_python" "VERSION" "$IMAGE_NAME"
            - env
            - popd
      - OUT: image_sample_python
    on_success:
      - script: echo 'succeeded'
    on_failure:
      - script: echo 'failed'
    flags:
      - runsh

  - name: execute_tasks_list
    type: runSh
    on_start:
      - NOTIFY: slack
    runtime:
      architecture: x86_64
      os: Ubuntu_16.04
      container: true
    steps:
      - IN: reg_dh_ric03uec
      - IN: sample_python_runCI
      - IN: global_state
        switch: off
      - TASK:
          name: host_check_OS
          runtime:
            container: false
            options:
              env:
                - ENV1: VALUE1
                - ENV2: VALUE2
          script:
            - docker images
            - uname -a
            - df -h
            - cat /etc/os-release
            - env
      - TASK:
          name:  container_check_OS
          runtime:
            options:
              env:
                - CONTAINER_ENV3: VALUE3
                - CONTAINER_ENV4: VALUE4
              imageName: drydock/u14pytall
              imageTag: master
          script:
            - echo "Checking container os version"
            - cat /etc/*-release
            - df -h
            - env
            - echo "$BUILD_NUMBER" > job_state.txt
            - shipctl copy_file_to_state "job_state.txt"
      - TASK:
          runtime:
            options:
              imageName: drydock/u14pytall
              imageTag: master
              pull: true
          script:
            - echo "sleeping for a while..."
            - sleep 30
            - shipctl copy_file_from_prev_state "job_state.txt" "prev_state.txt"
            - cat prev_state.txt || true
            - cp -vr job_state.txt $BUILD_DIR/OUT/global_state/state/
      - OUT: global_state
    on_success:
      - script: echo "successfully completed"
      - NOTIFY: slack
    on_failure:
      - script: echo "Oops !!! something went wrong"
      - NOTIFY: slack
    flags:
      - runSh

  - name: job_with_no_runtime
    type: runSh
    steps:
      - IN: reg_dh_ric03uec
      - IN: execute_tasks_list
        switch: off
      - IN: global_state
        switch: off
      - IN: nginx-img
        pull: true
      - TASK:
          name: host_check_OS
          script:
            - uname -a
            - df -h
            - sudo docker images
            - cp -vr $BUILD_DIR/IN/global_state/state/job_state.txt .
            - cat job_state.txt
    flags:
      - runSh

  - name: job_with_runtime
    type: runSh
    runtime:
      architecture: x86_64
      os: Ubuntu_16.04
    steps:
      - IN: reg_dh_ric03uec
      - IN: execute_tasks_list
        switch: off
      - IN: nginx-img
        pull: false
      - IN: global_state
        switch: off
      - TASK:
          name: host_check_OS
          script:
            - uname -a
            - df -h
            - sudo docker images
            - cp -vr $BUILD_DIR/IN/global_state/state/job_state.txt .
            - cat job_state.txt
    flags:
      - runSh

  - name: failed_job
    type: runSh
    runtime:
      architecture: x86_64
      os: Ubuntu_16.04
      container: false
    steps:
      - IN: reg_dh_ric03uec
      - IN: execute_tasks_list
        switch: off
      - IN: global_state
        switch: off
      - TASK:
          name: host_check_OS
          runtime:
            options:
              env:
                ENV5: VALUE5
                ENV6: VALUE6
          script:
            - uname -a
            - df -h
            - cat /etc/os-release
            - sudo docker info
            - sudo docker images
            - cp -vr $BUILD_DIR/IN/global_state/state/job_state.txt .
            - this is an invalid command, should fail
    on_success:
      - script: echo "successfully completed"
      - NOTIFY: slack
    on_failure:
      - script: echo "Oops !!! something went wrong"
      - NOTIFY: slack
    flags:
      - runSh

  - name: aarch64_host_job
    type: runSh
    runtime:
      architecture: aarch64
      os: Ubuntu_16.04
      container: false
    steps:
      - IN: sample_python_runCI
      - IN: reg_dh_ric03uec
        switch: off
      - TASK:
          name: check host architecture
          runtime:
            options:
              env:
                ENV_FOO: FOO
                ENV_BAR: BAR
          script:
            - echo "executing PRE_TASK steps 2"
            - echo "executing PRE_TASK steps 4"
            - uname -a
            - ps aux | wc -l
      - TASK:
          name: test_task_1
          runtime:
            container: false
          script:
            - echo "executing POST_TASK steps 2"
            - echo "executing POST_TASK steps 3"
    on_success:
      - script: echo 'on success !!!!!'
    on_failure:
      - script: 'echo ''Failed job .... :('''
    always:
      - script: echo 'this will always run'
